// Popular Indian cities used as autocomplete suggestions across
// location inputs (profile, new listing, browse filter).
export const INDIAN_CITIES = [
  "Bengaluru",
  "Mumbai",
  "Delhi",
  "New Delhi",
  "Gurugram",
  "Noida",
  "Ghaziabad",
  "Faridabad",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Surat",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Bhopal",
  "Chandigarh",
  "Mohali",
  "Panchkula",
  "Kochi",
  "Thiruvananthapuram",
  "Kozhikode",
  "Coimbatore",
  "Madurai",
  "Tiruchirappalli",
  "Mysuru",
  "Mangaluru",
  "Visakhapatnam",
  "Vijayawada",
  "Guntur",
  "Nashik",
  "Nagpur",
  "Aurangabad",
  "Vadodara",
  "Rajkot",
  "Patna",
  "Ranchi",
  "Bhubaneswar",
  "Cuttack",
  "Guwahati",
  "Shillong",
  "Dehradun",
  "Rishikesh",
  "Haridwar",
  "Amritsar",
  "Ludhiana",
  "Jalandhar",
  "Varanasi",
  "Prayagraj",
  "Agra",
  "Meerut",
  "Jodhpur",
  "Udaipur",
  "Jammu",
  "Srinagar",
  "Goa",
  "Panaji",
] as const;

// Common Bengaluru/Mumbai/Delhi/Hyderabad micro-locations to help refine "area, city" entries.
export const INDIAN_AREAS = [
  "Koramangala, Bengaluru",
  "Indiranagar, Bengaluru",
  "HSR Layout, Bengaluru",
  "Whitefield, Bengaluru",
  "Electronic City, Bengaluru",
  "Jayanagar, Bengaluru",
  "Marathahalli, Bengaluru",
  "Powai, Mumbai",
  "Andheri, Mumbai",
  "Bandra, Mumbai",
  "Malad, Mumbai",
  "Thane, Mumbai",
  "Dadar, Mumbai",
  "Connaught Place, New Delhi",
  "Saket, New Delhi",
  "Dwarka, New Delhi",
  "Karol Bagh, New Delhi",
  "Rohini, New Delhi",
  "HITEC City, Hyderabad",
  "Gachibowli, Hyderabad",
  "Madhapur, Hyderabad",
  "Banjara Hills, Hyderabad",
  "Kondapur, Hyderabad",
  "Kothrud, Pune",
  "Hinjewadi, Pune",
  "Baner, Pune",
  "Viman Nagar, Pune",
  "Kharadi, Pune",
  "Salt Lake, Kolkata",
  "New Town, Kolkata",
  "Park Street, Kolkata",
  "Anna Nagar, Chennai",
  "T. Nagar, Chennai",
  "Velachery, Chennai",
  "OMR, Chennai",
  "Adyar, Chennai",
  "Cyber City, Gurugram",
  "Sohna Road, Gurugram",
  "Sector 62, Noida",
  "Sector 18, Noida",
] as const;

export const INDIAN_LOCATION_SUGGESTIONS = [...INDIAN_AREAS, ...INDIAN_CITIES];
